### PR TITLE
arguably better blank line handling

### PR DESCRIPTION
**Pull request by landfillbaby**
the previous implementation had a problem when the first lines are blank
i'm sending this pr to you since i based it on your branch
also now uses a global variable, in case of files without trailing newlines

### CODE REVIEW

**Comment by obfusk** [comment]
> the previous implementation had a problem when the first lines are blank

I see it doesn't work well with spaces/tabs and `--background`. Did you mean that?

> also now uses a global variable, in case of files without trailing newlines

I didn't think of that. Since (non-empty) files without a newline at the end are not actually text files according to POSIX, I don't really take those into account normally; but probably useful for windows users. :+1: 

Unfortunately, your version doesn't work well with `--change-empty`, changing colour every character.

**Comment by landfillbaby** [comment]
ok it definitely works now! oops
in that first commit i completely forgot to actually fix the problem with leading blank lines, i missed a part i had changed in my personal lightweight c reimplementation that only does `--trans --bi`

**Comment by landfillbaby** [comment]
in that first commit i completely forgot to actually fix the problem with leading blank lines, i missed a part i had changed in my personal lightweight c reimplementation that only does `--trans --bi`

**Comment by landfillbaby** [comment]
oops. sorry

**Comment by obfusk** [comment]
That does seem better. I closed my PR and suggest you open one upstream with your version.

**Comment by obfusk** [comment]
@landfillbaby You weren't kidding about the "lightweight" part :smile:.
Now my [python version](https://github.com/obfusk/proudcat) looks a lot bigger.

**Comment by obfusk** [comment]
@landfillbaby my python version also doesn't colour trailing whitespace (which is relevant w/ `--background`).

**Comment by landfillbaby** [comment]
oh cool! i think the c++ version would require a pretty big rewrite to support that though

**Comment by obfusk** [comment]
@landfillbaby since I was planning on learning more rust, I wrote a [rust version](https://github.com/obfusk/proudcat-rust) as well :sweat_smile:

**Comment by landfillbaby** [comment]
nice! i have news too! i just wrote a version that fills the whole screen with background instead of just the part with text, that way lines won't need to be skipped to begin with. i think the thing we're currently doing should be renamed from background to highlighting
it's currently only implemented as [a C program in my repo](https://github.com/landfillbaby/pridecat/blob/main/pridebg-lite-trans-bi.c)

**Comment by obfusk** [comment]
Nice! I implemented it as well on [this branch of my rust version](https://github.com/obfusk/proudcat-rust/tree/bg-erase-line).

**Comment by obfusk** [comment]
@landfillbaby FYI termux/termux-app#1610

**Comment by landfillbaby** [comment]
nice! i was thinking of doing that too but i had just chosen to ignore the variable in my version and just assume it's on a modern terminal.

**Comment by obfusk** [comment]
@landfillbaby I made some improvements to my python & rust versions.

**Comment by landfillbaby** [comment]
nice, i like your dynamic choice of black or white text

**Comment by landfillbaby** [comment]
i sent a pr just now though for changing the flag patterns a bit

**Pull request closed without merging**
